# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    commands:
      - echo Install any other dependencies 
      #- npm install 
      - npm install react
      - npm install superagent
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install      
  build:
    commands:
      - echo Build 
      - npm run build
      - cd build
  post_build:
    commands:
      - echo no post build activity
      #- zip -r spaforcicd.zip build
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
artifacts:
  files:
    # build/*
    - index.html
    - service-worker.js
    - asset-manifest.json
    - static/*
    - static/css/*
    - static/js/*
    - static/css/main.dfc9c75c.css
    - static/css/main.dfc9c75c.css.map
    - static/js/main.af4c29a0.js
    - static/js/main.af4c29a0.js.map
