# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    commands:
      - echo Install any other dependencies 
      #- npm install 
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install      
  build:
    commands:
      - echo Build 
      - npm run build
  post_build:
    commands:
      - zip -r spaforcicd.zip build
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
artifacts:
  files:
    - build/*
